###
GET localhost:8082/genres

###
GET localhost:8082/genres/4242?trace=true&message=true

###
POST localhost:8082/genres
Content-Type: application/json

{"name":"science-fiction"}

###
DELETE localhost:8082/genres/4242

###
PUT localhost:8082/genres/42
Content-Type: application/json

{"name":"Science-Fiction"}